export const BUSINESS = {
  name: "CallKaarigar",
  legalName: "CallKaarigar",
  tagline: "Skilled workers on a phone call.",
  description:
    "CallKaarigar connects customers in Goa with trusted electricians, plumbers, painters, and other skilled workers — by phone. No app download required.",
  website: "https://callkaarigar.in",
  email: "hello@callkaarigar.in",
  address: {
    street: "Sankhali",
    locality: "Sankhali",
    region: "Goa",
    postalCode: "403505",
    country: "IN",
    formatted: "Sankhali, Goa, India",
  },
  hours: [
    { days: "Monday – Saturday", open: "9:00 AM", close: "7:00 PM" },
    { days: "Sunday", open: null, close: null, note: "Closed" },
  ],
  timezone: "Asia/Kolkata",
  profileImage: "/assets/web-app-manifest-512x512.png",
  catalog: [
    "Electrician",
    "Plumber",
    "Painter",
    "Mason",
    "Carpenter",
    "AC Technician",
    "Locksmith",
    "Tile Worker",
    "Welder",
    "CCTV Installer",
    "Pest Control",
    "Cleaning Service",
    "Waterproofing",
    "False Ceiling",
    "Appliance Repair",
    "Geyser Repair",
    "Glass Fabricator",
    "Solar Installer",
    "Civil Work",
    "Interior Texture",
  ],
} as const;
